language: php
php:
  - 5.4
mysql:
  adapter: mysql2
  database: wp_travis
  username: root
  encoding: utf8
before_script:
  - "mysql -e 'create database wp_travis;'"
  - wget http://wordpress.org/latest.tar.gz
  - tar xfz latest.tar.gz
  - cd wordpress
  - rm -rf wp-content/
  - cp -rpf * ../
  - cd ..
  - rm -rf wordpress/
  - rm -f latest.tar.gz
  - cp wp-content/travis-config.php wp-config.php