# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.3

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# mysql credentials - db name = wp_travis; user = root; pass = ""; host = localhost;
mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: wp_travis

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - "mysql -e 'create database wp_travis;'"
  - mysql wp_travis < wp-content/wp_travis.sql
  - wget http://wordpress.org/latest.tar.gz
  - tar xfz latest.tar.gz
  - rm -rf wordpress/wp-content/
  - cp -rpf wordpress/* .
  - cp wp-content/wp-config-sample.php wp-config.php
  - cp wp-content/unittests-config-sample.php wp-content/plugins/wp-tests/unittests-config.php
  - git submodule add git://github.com/c10b10/dotvim.git
  - git submodule init
  - git submodule update

# set the script to run when redy. defaults to phpunit
script: sh test.sh wp-content/plugins/wp-tests/