language: php
php:
  - 5.3
mysql:
  adapter: mysql2
  database: wp_travis
  username: root
  encoding: utf8
before_script:
  - "mysql -e 'create database wp_travis;'"
  - cd wp-content
  - mysql -u root -h localhost wp_travis < wp_travis.sql
  - "mysql -e 'DESCRIBE wp_options'"
  - cd ../
  - wget http://wordpress.org/latest.tar.gz
  - tar xfz latest.tar.gz
  - cd wordpress
  - rm -rf wp-content/
  - cp -rpf * ../
  - cd ..
  - rm -rf wordpress/
  - rm -f latest.tar.gz
  - cp wp-content/travis-config.php wp-config.php
  - cp wp-content/travis-unit-config.php wp-content/plugins/wp-tests/unittests-config.php