# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.3

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  - MYSQL_USER=root

mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: browserid

# execute any number of scripts before the test run, custom env's are available as variables
before_install:
  - "mysql -e 'create database wp_travis;'"
  - cd wp-content
  - mysql wp_travis
  - mysql < wp_travis.sql
  - mysql < show tables;
  - cd ../
before_script:
  - wget http://wordpress.org/latest.tar.gz
  - tar xfz latest.tar.gz
  - cd wordpress
  - rm -rf wp-content/
  - cp -rpf * ../
  - cd ..
  - rm -rf wordpress/
  - rm -f latest.tar.gz
  - cp wp-content/travis-config.php wp-config.php
  - cp wp-content/travis-unit-config.php wp-content/plugins/wp-tests/unittests-config.php